name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # or master, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Change this if you have a specific directory for your static files
          publish_branch: gh-pages # This is the branch where your site will be deployed
